version: '3.8'

services:
  backend:
    build:
      context: ./api
    container_name: api
    ports:
      - "3001:3001"
    env_file:
    - ./api/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    container_name: client
    ports:
      - "5173:5173"  
    env_file:
    - ./client/.env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

