version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - finance-network


  backend:
    build:
      context: ./api
    container_name: api
    ports:
      - "3001:3001"
    env_file:
    - ./api/.env
    networks:
      - finance-network


  frontend:
    build:
      context: ./client
    container_name: client
    ports:
      - "5173:5173"  
    env_file:
    - ./client/.env
    depends_on:
      - backend
    networks:
      - finance-network

volumes:
  mongo-data:

networks:
  finance-network:
    driver: bridge

